#!/bin/sh
#
# Start/stop bluealsa
#

NAME=bluealsa
DAEMON="/usr/bin/$NAME"

case "$1" in
start)
  echo "Starting $NAME..."
  start-stop-daemon -S -b -x "$DAEMON" -n "$NAME" -- -p a2dp-sink
  [ $? -eq 0 ] && echo "OK" || echo "ERROR"
  ;;
stop)
  echo "Stopping $NAME..."
  start-stop-daemon -K -n "$NAME" -o
  [ $? -eq 0 ] && echo "OK" || echo "ERROR"
  ;;
restart)
  "$0" stop
  "$0" start
  ;;
*)
  echo "Usage: $0 {start|stop|restart}"
  exit 1
esac
